<?php

namespace Database\Seeders;

use App\Models\Joueur;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JoueurSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('joueurs')->insert(
            [
                [
                    'nom'=>'leRpz',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Spain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>11,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Albania',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
               
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>6,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'McCain',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>3,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'Ghost',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>1,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'Ghost',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>1,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'Ghost',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>1,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'Boum',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>1,
                    // 'photo_id'=>3,
                ],
                [
                    'nom'=>'Pim',
                    'prenom'=>'Ben',
                    'age'=>'26',
                    'genre'=>'Homme',
                    'nat'=>'Américain',
                    'poste'=>'Avant',
                    'tel'=>'0034 56 76 87 88',
                    'email'=>'maccain@gamail.com',
                    'equipe_id'=>1,
                    // 'photo_id'=>3,
                ],
    
            ]
        );
        

    }
}
